on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'print floder before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'print floder after'
        run: ls -a


